import type { HttpClient } from '../http.js';

export type WorkflowStatus = 'draft' | 'active' | 'inactive' | 'error';
export type StepType = 'trigger' | 'action' | 'condition' | 'switch' | 'delay' | 'loop' | 'ai_intent' | 'ai_agent' | 'approval' | 'end';

export interface WorkflowStep {
  id: string;
  step_type: StepType;
  name: string | null;
  action_id: string | null;
  action_name: string | null;
  config: Record<string, unknown>;
  position_x: number | null;
  position_y: number | null;
  step_order: number;
  guidance: string | null;
  on_success_step_id: string | null;
  on_failure_step_id: string | null;
}

export interface StepInput {
  /** A real, already-persisted step id (editing an existing node) or a client-generated temp id (a new node) — both resolve through the same id-map. */
  id?: string;
  step_type: StepType;
  name?: string;
  /** Required when step_type is 'action'. */
  action_id?: string;
  config?: Record<string, unknown>;
  position_x?: number;
  position_y?: number;
  guidance?: string;
  on_success_ref?: string | null;
  on_failure_ref?: string | null;
}

export interface Workflow {
  id: string;
  tenant_id: string;
  name: string;
  workflow_key: string;
  description: string | null;
  is_active: boolean;
  status: WorkflowStatus;
  trigger_type: string;
  trigger_config: { slug: string; has_secret: boolean } | null;
  created_at: string;
  updated_at: string;
  steps: WorkflowStep[];
  /** Present only on list()/get() results — how to call this workflow over the API, absent from create/update/toggle responses. */
  endpoint?: string;
  method?: string;
  inputSchema?: Record<string, unknown>;
}

export interface CreateWorkflowInput {
  name: string;
  description?: string;
  steps?: StepInput[];
}

export interface UpdateWorkflowInput {
  name?: string;
  description?: string;
  /** Freely renameable — must be unique within the tenant. */
  workflow_key?: string;
  /** Upsert-by-id — omitted existing step ids are deleted, not merely left alone. */
  steps?: StepInput[];
}

export interface DeployResult {
  workflow: Workflow;
  /** Present only when a webhook secret was newly generated by this call. */
  webhook_url?: string;
  /** Plaintext, shown once. Present only when newly generated by this call — capture it immediately, it is never returned again. */
  webhook_secret?: string;
}

export interface RotateWebhookSecretResult {
  webhook_url: string;
  /** Plaintext, shown once — capture it immediately, it is never returned again. */
  webhook_secret: string;
  previous_secret_valid_until: string | null;
}

export interface RunWorkflowInput {
  input?: Record<string, unknown>;
  /** Resume a previously paused (needs_input) run. Omit to start fresh. */
  conversation_id?: string;
}

export interface WorkflowRunResult {
  run_id: string;
  conversation_id: string;
  status: 'completed' | 'needs_input' | 'failed';
  trace: unknown[];
  missing_parameter?: Record<string, unknown>;
}

/** One traced step — a webhook/action call, an ai_intent/ai_agent turn, a condition branch, etc. */
export interface WorkflowStepTrace {
  stepId: string;
  stepType: string;
  name: string | null;
  actionId?: string | null;
  actionName?: string | null;
  success: boolean;
  response?: unknown;
  error?: string;
  /** True when resumed from cached progress — the step's action was not re-called. */
  skipped?: boolean;
  durationMs?: number;
}

/**
 * Step-level, not token-level: no step type in a Workflow streams tokens,
 * so there's no delta to emit — `step` fires as each one is traced, and
 * `done` carries the complete trace in one piece.
 */
export type WorkflowRunStreamEvent =
  | { type: 'step'; step: WorkflowStepTrace }
  | ({ type: 'done' } & WorkflowRunResult)
  | { type: 'error'; code: string; message: string };

export interface WorkflowRunSummary {
  id: string;
  status: string;
  trigger: string;
  started_at: string;
  completed_at: string | null;
  total_latency_ms: number | null;
  step_count: number;
  input: Record<string, unknown>;
}

export interface Pagination {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface ListOptions {
  page?: number;
  pageSize?: number;
  status?: string;
}

function toQuery(options: ListOptions = {}): string {
  const params = new URLSearchParams();
  if (options.page !== undefined) params.set('page', String(options.page));
  if (options.pageSize !== undefined) params.set('pageSize', String(options.pageSize));
  if (options.status !== undefined) params.set('status', options.status);
  const qs = params.toString();
  return qs ? `?${qs}` : '';
}

/**
 * Multi-step graphs of intents/agents/actions/conditions. Mirrors the full
 * /v1/workflows surface (see openapi.yaml): CRUD + toggle/deploy/webhook-
 * secret-rotate, plus run/run-history. {workflowIdOrKey} in every method
 * below accepts either the database id or the human-readable workflow_key.
 */
export class WorkflowsResource {
  constructor(private readonly http: HttpClient) {}

  async list(): Promise<Workflow[]> {
    return this.http.get<Workflow[]>('/v1/workflows');
  }

  async get(workflowIdOrKey: string): Promise<Workflow> {
    return this.http.get<Workflow>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}`);
  }

  async create(input: CreateWorkflowInput): Promise<Workflow> {
    const { workflow } = await this.http.post<{ workflow: Workflow }>('/v1/workflows', input);
    return workflow;
  }

  async update(workflowIdOrKey: string, input: UpdateWorkflowInput): Promise<Workflow> {
    const { workflow } = await this.http.patch<{ workflow: Workflow }>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}`, input);
    return workflow;
  }

  /** Flips is_active on an already-deployed workflow. Blocked on a draft (throws DEPLOY_REQUIRED) — deploy() it first. */
  async toggle(workflowIdOrKey: string): Promise<Workflow> {
    const { workflow } = await this.http.patch<{ workflow: Workflow }>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/toggle`);
    return workflow;
  }

  /**
   * The draft->published transition. On first deploy of a webhook-triggered
   * workflow, also mints the webhook infrastructure and returns the secret
   * exactly once — capture `webhook_secret` from the result immediately, it
   * is never retrievable again.
   */
  async deploy(workflowIdOrKey: string): Promise<DeployResult> {
    return this.http.post<DeployResult>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/deploy`);
  }

  /**
   * Only valid for a webhook-triggered, already-deployed workflow. The
   * previous secret stays valid for `gracePeriodSeconds` (default 300, max
   * 3600) so external senders can roll over without downtime; pass 0 for an
   * immediate hard cutover. The new secret is returned exactly once.
   */
  async rotateWebhookSecret(workflowIdOrKey: string, gracePeriodSeconds?: number): Promise<RotateWebhookSecretResult> {
    return this.http.post<RotateWebhookSecretResult>(
      `/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/webhook-secret/rotate`,
      gracePeriodSeconds === undefined ? undefined : { grace_period_seconds: gracePeriodSeconds },
    );
  }

  /** A hard delete — unlike Collections and Agents, there is no soft-delete/inactive state for a removed workflow. */
  async delete(workflowIdOrKey: string): Promise<void> {
    await this.http.delete<void>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}`);
  }

  async run(workflowIdOrKey: string, input: RunWorkflowInput = {}): Promise<WorkflowRunResult> {
    return this.http.post<WorkflowRunResult>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/run`, input);
  }

  /** Same input as run() — real-time step progress instead of a single awaited result. See WorkflowRunStreamEvent. */
  runStream(workflowIdOrKey: string, input: RunWorkflowInput = {}): AsyncGenerator<WorkflowRunStreamEvent, void, undefined> {
    return this.http.stream<WorkflowRunStreamEvent>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/run/stream`, input);
  }

  async listRuns(workflowIdOrKey: string, options: ListOptions = {}): Promise<{ runs: WorkflowRunSummary[]; pagination: Pagination }> {
    return this.http.get<{ runs: WorkflowRunSummary[]; pagination: Pagination }>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/runs${toQuery(options)}`);
  }

  async getRun(workflowIdOrKey: string, runId: string): Promise<Record<string, unknown>> {
    const { run } = await this.http.get<{ run: Record<string, unknown> }>(`/v1/workflows/${encodeURIComponent(workflowIdOrKey)}/runs/${encodeURIComponent(runId)}`);
    return run;
  }
}
